# Generated by Django 3.0.5 on 2020-05-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregisteration',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
