# Generated by Django 3.0.5 on 2020-05-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='selling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(max_length=10)),
                ('product_name', models.CharField(max_length=50)),
                ('product_image', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
