# Generated by Django 3.0.5 on 2020-05-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selling',
            name='product_des',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
