# Generated by Django 3.0.5 on 2020-05-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_selling_product_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selling',
            name='product_des',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
