# Generated by Django 3.0.5 on 2020-05-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200528_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selling',
            name='product_des',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
